@startuml
skinparam backgroundColor transparent
left to right direction

rectangle Guarderia {
  usecase "Ingresar" as ingresar
  usecase "Consultar Disponibilidad" as consultarDisponibilidad
  usecase "Consultar Fecha de compra" as consultarFechas
  usecase "Consultar Asignaciones de Zona" as consultarZonas
  usecase "Consultar Vehiculos asignados" as consultarVehiculos
  usecase "Vender Garage" as venderGarage
  usecase "Asignar Zona" as asignarZona
  usecase "Cerrar sesión" as cerrar

  
  actor "Administrador" as adm
  adm --> ingresar
  adm --> consultarDisponibilidad
  adm --> consultarFechas
  adm --> consultarZonas
  adm --> consultarVehiculos
  adm --> venderGarage
  adm --> asignarZona
  adm --> cerrar
  
  actor "Socio" as soc
  ingresar <-- soc
  consultarDisponibilidad <-- soc
  consultarFechas <-- soc
  cerrar <-- soc
  
  actor "Empleado" as emp
  ingresar <-- emp
  consultarZonas <-- emp
  consultarVehiculos <-- emp
  cerrar <-- emp
}

@enduml
