@startuml
skinparam backgroundColor transparent
left to right direction

rectangle Guarderia {
  usecase "Ingresar" as ingresar
  usecase "Consultar Datos" as consultarDatos
  usecase "Asignar Vehiculo a Garage" as asignarVehiculoAGarage
  usecase "Consultar Asignaciones de Zona" as consultarZonas
  usecase "Consultar Vehiculos asignados" as consultarVehiculos
  usecase "Vender Garage" as venderGarage
  usecase "Asignar Zona" as asignarZona
  usecase "Cerrar sesión" as cerrar

  usecase "Registrar Socio" as registrarSocio
  usecase "Registrar Empleado"  as registrarEmpleado
  usecase "Registrar Garage" as registrarGarage
  usecase "Registrar Vehiculo" as registrarVehiculo
  usecase "Registrar Zona" as registrarZona

  
  actor "Administrador" as adm
    adm --> ingresar
    adm --> consultarDatos
    adm --> venderGarage
    adm --> asignarZona
    adm --> cerrar
    adm --> asignarVehiculoAGarage
    adm --> registrarSocio
    adm --> registrarEmpleado
    adm --> registrarGarage
    adm --> registrarVehiculo
    adm --> registrarZona

  
  actor "Socio" as soc
    ingresar <-- soc
    consultarDatos <-- soc
    consultarVehiculos <-- soc
    cerrar <-- soc

  actor "Empleado" as emp
    ingresar <-- emp
    consultarDatos <-- emp
    consultarZonas <-- emp
    consultarVehiculos <-- emp
    cerrar <-- emp

}
@enduml