@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false

Class07 .. Class08

enum      TipoVehiculo {
  MOTORHOME
  CASARODANTE
  ARRASTRE
  CARAVANA
  TRAILER
}

class     Dimensiones {
  alto : Integer
  largo : Integer
  ancho : Integer
}
/'
**** Vehiculo Composicion con Dimensiones ****
**** Vehiculo Agregacion con TipoVehiculo ****
'/
Vehiculo o-- TipoVehiculo : tipo
Vehiculo *-- Dimensiones : dimensiones

class Vehiculo {
  matricula : String
  nombre : String
  fechaAsignacion : Date

    + Vehiculo(matricula:String, nombre:String, tipo:TipoVehiculo, dimensiones:Dimensiones)
    + setFechaAsignacion(fechaAsignacion:Date)

}

Vehiculo "*" <-- "1" Socio : vehiculosList

class     Garage {
  numero : Integer
  contadorLuz : Integer
  mantenimiento : Boolean
  fechaCompra : Date

    + Garage(numero:Integer,dimensiones:Dimensiones, Zona zona)
    + dimensionesAptas(Dimensiones) : Boolean
    + comprar(Socio)
    + leerContadorLuz : Integer
    + contratarMantenimiento()
    + guardarVehiculo(Vehiculo v)
    + estaLibre() : Boolean

}
/'
**** Garage Composicion con Vehiculo ****
**** Garage Agregacion con Zona ****
'/
Garage o-- Vehiculo : vehiculo
Garage o-- Zona : zona
Garage o-- Socio : socio
/'
**** Garage Agregacion con Socio **** ?? No se si es ideal...
'/

class     Guarderia {
  usuario : Usuario
  garages : List<Garage>

    -Guarderia()
    +getInstance():Guarderia

    + venderGarage(Garage g, Socio s)
    + leerContadorLuz(Garage g) : Integer

}

Guarderia *--> Garage : garages
Guarderia --> Usuario : usuario

class     Zona {
  letra : String
  capacidad : Integer
  cantidadVehiculos : Integer
  empleadosAsignados : List<Empleado>

  + Zona (letra:String, capacidad:Integer, cantidadVehiculos:Integer)
    + getCantidadVehiculos() : Integer


}

Zona o-- Dimensiones : dimensionGarages
Zona "1" *-- "many" TipoVehiculo : vehiculosAdminitos
Zona "1" *-- "many" Empleado : empleadosAsignados


abstract class Usuario {
  nombre : String
  password : String
  direccion : String
  telefono : String
}

class     Socio {
  fechaIngreso : Date
  dni : Long

    + consultarDisponibilidad(Vehiculo v) : Boolean
    + agregarVehiculo(Vehiculo v)

}

class     Empleado {
  codigo : Integer
  especialidad : String

  asignaciones : List<Zona>

    + getAsignaciones() : List<Zona>



}

class     Administrador {


}

Usuario <|-- Administrador
Usuario <|-- Empleado
Usuario <|-- Socio


Class EntradaSalida {
  +leerCadena(textoDelMensaje : String) : String
  +leerDouble(textoDelMensaje : String) : Float
  +leerInt(textoDelMensaje : String) : Integer
  +mostrarMensaje(textoDelMensaje : String)
  +leerPassword(textoDelMensaje : String)
}

Class Menu {


}


@enduml
